spring:
  application:
    name: teacher-management

  # H2 in-memory database — chạy được ngay, không cần cài PostgreSQL
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  h2:
    console:
      enabled: true # Truy cập UI tại http://localhost:8080/h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop # Tự tạo bảng khi start, xóa khi stop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    enabled: false

server:
  port: 8080
